# Generated by Django 4.2.6 on 2023-12-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_canchas/'),
        ),
    ]
