# Generated by Django 4.2.6 on 2023-12-13 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbolito', '0003_preciocancha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancha',
            name='horarios_disponibles',
            field=models.JSONField(default=list),
        ),
    ]
