# Generated by Django 4.2.6 on 2023-12-20 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbolito', '0004_cancha_horarios_disponibles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='fecha_fin',
        ),
    ]
