# Generated by Django 4.2.6 on 2023-12-22 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbolito', '0005_remove_reserva_fecha_fin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cancha',
            old_name='horarios_disponibles',
            new_name='horarios_detalles',
        ),
    ]
